services:
  db:
    image: postgres:latest
    container_name: test_users_db_container
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d test_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend#
    depends_on:
      db:
        condition: service_healthy
    command: flask run --host=0.0.0.0
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
