name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Start Docker services
        run: |
          docker compose -f docker-compose.yaml up -d --build
          docker compose ps
        env:
          POSTGRES_USER: testuser 
          POSTGRES_PASSWORD: testpassword 
          POSTGRES_DB: test_db 
          DATABASE_URL: postgresql://testuser:testpassword@db:5432/test_db
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          flake8 --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run database migrations
        run: |
          docker compose exec web flask db upgrade

      - name: Test with Pytest
        run: |
          docker compose exec web pytest
